server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. Rota do Backend (Proxy Reverso para o Java)
    # Se o navegador do cliente pedir qualquer coisa que comece com /api/...
    location /api/ {
        # O Nginx repassa a requisição para o container do Java pela rede interna do Docker
        # NOTA: 'backend' é o nome do serviço do Java no docker-compose.yml
        proxy_pass http://backend:8080/api/;
        
        # Repassa os cabeçalhos originais para o Java saber quem fez a requisição
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}