name: Backend CD - Deploy no Notebook

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar arquivo .env Raiz
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> .env
          echo "FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}" >> .env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env

      - name: Criar arquivo .env do Frontend
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> frontend/.env

      - name: Subir a aplicação com Docker Compose
        run: |
          docker compose down
          docker compose up -d --build
