name: Backend CD - Deploy no Notebook

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Subir a aplicação com Docker Compose
        run: |
          docker-compose down
          docker-compose up -d --build
